version: '3.7'

volumes:
  pgdata:

services:
  app:
    image: http4s-web-novel/http4s-web-novel:latest<skipPull>
    links:
      - postgres
      - openTel
    environment:
      - T4C_COLLECTOR_HOST=openTel
      - T4C_COLLECTOR_PORT=9411
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - openTel

  postgres:
    image: postgres:14.3
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  openTel:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.51.0
    ports:
      - "9411:9411"
